name: run all tests

on:
  push:
    branches:
      'manual'
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest  # Изменено на Ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      - name: Set PATH
        run: echo "$GITHUB_PATH" >> $GITHUB_ENV

      - name: Check Allure version
        run: allure --version

      - name: Run tests with TestNG XML
        run: mvn test -DsuiteXmlFile=testng.xml

      - name: Allure report
        uses: afiore/action-allure-report@v0.1.0
        with:
          results-dir: target/allure-results     # Директория с результатами тестов
          report-dir: target/allure-report       # Директория для HTML-отчета

      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report
        if: always()

      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
          publish_branch: gh-pages  # Ветка, на которую будете публиковать
