name: run all tests

on:
  push:
    branches:
      'manual'
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install Scoop
        run: |
           iwr get.scoop.sh -useb | iex

      - name: Install Allure
        run: |
           scoop install allure

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Java
        uses: actions/cache@v4
        with:
          path: ~/.sdkman/candidates/java
          key: ${{ runner.os }}-java-${{ hashFiles('**/pom.xml') }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: C:/Users/runneradmin/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Chrome
        uses: actions/cache@v4
        with:
          path: ~/.cache/google-chrome
          key: ${{ runner.os }}-chrome-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-chrome-

      - name: Cache ChromeDriver
        uses: actions/cache@v4
        with:
          path: ~/.cache/chromedriver
          key: ${{ runner.os }}-chromedriver-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-chromedriver-

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      # - name: Install Scoop
      #   run: |
      #     iwr get.scoop.sh -useb | iex

      # - name: Install Allure
      #   run: |
      #     scoop install allure

      - name: Set PATH
        run: echo "$GITHUB_PATH" >> $GITHUB_ENV

      - name: Check Allure version
        run: allure --version

      - name: run all tests
        run: mvn test

      - name: Allure report
        uses: afiore/action-allure-report@v0.1.0
        with:
          results-dir: allure-results     # Директория с результатами тестов
          report-dir: allure-report       # Директория для HTML-отчета

      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report
        if: always()

      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
          publish_branch: gh-pages  # Ветка, на которую будете публиковать
