name: nightly build at 11pm

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  nightly_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run all tests
        run: mvn test

      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

      - uses: actions/upload-artifact@master
        with:
          name: apitest.war
          path: ./target/*dineapitests*.war
      
