name: run all tests

on:
  push:
    branches:
      'simpleRun'

jobs:
  run-unit-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chromedriver-version: latest

      - name: run all tests
        run: mvn test

      - name: Generate Allure Report
        run: |
            allure generate target/allure-results -o target/allure-report
          if: always()  # Генерация отчета даже при падении тестов

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report