name: run all tests

on:
  push:
    branches:
      'simpleRun'

jobs:
  run-unit-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Java
        uses: actions/cache@v4
        with:
          path: ~/.sdkman/candidates/java
          key: ${{ runner.os }}-java-${{ hashFiles('**/pom.xml') }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Chrome
        uses: actions/cache@v4
        with:
          path: ~/.cache/google-chrome
          key: ${{ runner.os }}-chrome-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-chrome-

      - name: Cache ChromeDriver
        uses: actions/cache@v4
        with:
          path: ~/.cache/chromedriver
          key: ${{ runner.os }}-chromedriver-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-chromedriver-

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      - name: run all tests
        run: mvn test

      - name: Install Allure
        run: |
          choco install allure  # Для Windows

      - name: Check Allure version
        run: allure --version

      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report
        if: always()

      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
          publish_branch: gh-pages  # Ветка, на которую будете публиковать