name: Check by type

on:
  pull_request:
    types: ['opened', 'edited', 'reopened']

jobs:
  pr-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: run unit tests
        run: mvn test

